# docker-compose.yml
services:
  db:
    image: postgres:15
    container_name: user-profile-postgres
    environment:
      POSTGRES_DB: user_profiles
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: